### PR TITLE
added bound_correction_thresh to IndependentBounds

### PR DESCRIPTION
**Pull request by zsunberg**
I think this is the best way to deal with the annoying bounds warnings when the bounds only differ by numerically small amounts. Any comments?

### CODE REVIEW

**Comment by zsunberg** [comment]
@andreea7b does this seem like it would be a good solution to all those warnings?

**Comment by zsunberg** [comment]
haha, I just realized having "bound" in the name is totally redundant and meaningless. will change

**Comment by lassepe** [comment]
I also tested this with our use case and it works like a charm.

CC: @andreea7b

**Comment by zsunberg** [comment]
Cool, thanks

**Pull request merged**
